// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzfMcoXTcRqggQiImu83HfZ1wgrP43iOs',
    appId: '1:631981805180:web:7f07960b48cbfaf006c3f9',
    messagingSenderId: '631981805180',
    projectId: 'kuliku-auth',
    authDomain: 'kuliku-auth.firebaseapp.com',
    storageBucket: 'kuliku-auth.appspot.com',
    measurementId: 'G-ZHWVFETSHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Y0Vs8bFF2pjjMCTYMEADGShwAbrlTdI',
    appId: '1:631981805180:android:f9bf641a43e57ae606c3f9',
    messagingSenderId: '631981805180',
    projectId: 'kuliku-auth',
    storageBucket: 'kuliku-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3Mp0ZeKU05_CvNhwuLS5mhVkzVqZ2-Y',
    appId: '1:631981805180:ios:f812b991c9cae9c306c3f9',
    messagingSenderId: '631981805180',
    projectId: 'kuliku-auth',
    storageBucket: 'kuliku-auth.appspot.com',
    iosClientId:
        '631981805180-p9opqk4pd0oe0at0pt0r3b0svkaeksp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneKuliku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ3Mp0ZeKU05_CvNhwuLS5mhVkzVqZ2-Y',
    appId: '1:631981805180:ios:f812b991c9cae9c306c3f9',
    messagingSenderId: '631981805180',
    projectId: 'kuliku-auth',
    storageBucket: 'kuliku-auth.appspot.com',
    iosClientId:
        '631981805180-p9opqk4pd0oe0at0pt0r3b0svkaeksp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneKuliku',
  );
}
